server:
  port: 8080
user:
  name: L
  age: 27

spring:
  #http
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  #mail
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: binlingexia@163.com
    password: ming
  #mysql
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
 #redis
  redis:
    database: 1
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
    timeout: 0
 #thymeleaf
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    suffix: .html·
    prefix: classpath:/templates/
  #mongodb
  mongodb:
    host: localhost
    port: 27017
    username:
    password:
    database: demo
    authentication-database:
  #elasticsearch
  elasticsearch:
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.205:9300
      repositories:
        enabled: true
      cluster-name: industry_search












